### ISSUE TITLE
Agent Versions wrongly grouped in "Multible versions" tab

### ISSUE THREAD

**Issue by doesterr** [newrelic/nr1-groundskeeper#10]
## Description
I see a couple of my applications in the "Multiple versions" tab, showing versions like:
", 6.7.0.359"
", 6.8.0.360"

The pattern seems to be: "EMPTY_VERSION, REAL_VERSION"

When I check the applications in APM Settings/Environment, I see that they are only using one version, and not multiple.

## Steps to Reproduce

- I've deployed and subscribed the STABLE channel.
- Open the Agents Groundkeeper
- Check the "Multiple versions" tab

## Expected Behaviour

As long as I don't have multiple agent versions running, I should not see applications in the "Multiple versions" tab.

## Additional context

- Affected apps stayed in the "Multiple versions" tab, even after we've upgraded all hosts of those apps to use the latest agent versions
- I believe I've seen one or two apps that previously correctly showed up in "Up to date" with  "6.8.0.360" are now showing up in "Multiple versions" with ", 6.8.0.360"

**Comment by fightingmonk** [comment]
Hi @doesterr thanks for the bug report. I'm pretty sure I know what's going on here and can get this fixed this week... I'll follow up if we need any more info.

**Comment by doesterr** [comment]
Hey, I've just observed something interesting with this:

I was looking at the Agent Groundkeeper table about an hour, and saw that only a couple of applications were still wrongly reported as having multiple versions.

So over the next minutes I kept refreshing the page, seeing one application after another appear correctly in the "up to date" column, until the only application left in "multiple versions" was the one actually using multiple versions right now.

Right now, when I load the Agent Groundkeeper, I see everything reverted back to to the previous (wrong) state, with lot's of applications showing up in the multiple versions column, without actually running multiple agent versions.

**Comment by fightingmonk** [comment]
Hey @doesterr, thanks for hanging in there. I was able to repro your issue and with the fix we just pushed I'm not seeing it any more. Let me know how it works for you.

**Comment by doesterr** [comment]
@fightingmonk looks good when I start the nerdpack locally, but I get an error that version 0.3.1 is not found when I try to install it. Happens with all channels DEV|BETA|STABLE

```
➜  nr1-groundskeeper git:(master) nr1 nerdpack:deploy -c DEV
✖  Error: Nerdpack 83c90c7c-8b1c-457c-973f-e5830318d43f with version 0.3.1 not found
```

**Comment by tangollama** [comment]
@doesterr, the issue might be that the uuid in the Nerdpack is not the same one you have deployed. Your nerdpack uuid needs to be associated with the New Relic account that issued your API key. Can you confirm that?

**Comment by doesterr** [comment]
@tangollama by bad, I didn't publish the code before trying to deploy it. Got the latest version running and deployed - thanks!
