### ISSUE TITLE
Downloadable CSV of agent version report

### ISSUE THREAD

**Issue by fightingmonk** [newrelic/nr1-groundskeeper#24]
Downloadable CSV of agent version report

## Summary

The web ui for viewing agent age data is great but there are times when I want to export the whole dataset and throw it into a spreadsheet I can manipulate, annotate, and share with others.

## Desired Behaviour / Solution

When viewing the agent age report, I want to click a button and have the browser download a CSV-format file. It should combine data for all tables (up to date, out of date, multi-agent, no version) and an additional column indicating which table that app would appear in.

Columns:

Account Id, Account name, AppId, App name, Language, Agent version(s), Status

**Comment by devfreddy** [comment]
Just an FYI to whomever lands on this issue, there is some code in https://github.com/newrelic/nr1-donor-analyzer for downloading a CSV, would be relatively easy to grab that and implement here.

**Comment by aso1124** [comment]
CSV downloads are now available in v2.0!
