### ISSUE TITLE
Redesign groundkeeper UI

### ISSUE THREAD

**Issue by danielgolden** [newrelic/nr1-groundskeeper#3]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary
It doesn't look like this nerdpack, as useful as it is, has had much design attention up to this point. A thoughtful redesign would improve the user experience by quite it a bit, so I'm going to take some time to work on a redesign that I can recommend in a PR.

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

## Desired Behaviour
Exactly the behavior that it already has, but with the application of ui design best practices and a visual style that aligns matches that of NR1.

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Possible Solution
A redesign! Wireframe and mockups to come in the comments...

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context
This matters to me because I think it's important that the open source applications that we release as an org meet our standard of design and UX. Most/if not all of the folks building these apps aren't designers. This happens to be my specialty, so here we go!

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by danielgolden** [comment]
### Wireframe v1 
Here's what I'm thinking right now. I'd bet that a lot about this plan is going to change, but if I have to put this on pause I want to know where I left off. Feedback welcome!

<img width="1440" alt="V1" src="https://user-images.githubusercontent.com/812989/68034155-8ef20e00-fc97-11e9-9b1e-b30d4224fcc9.png">

- Latest versions sidebar on the right because IMO it's ancillary helpful information.
- Upgrade SLO in a dropdown rather than radio buttons because it's configuration, rather than just a regular form. Also if more options need to be added, it will become a mess fast
- "To value" dropdown is only displayed when "filter apps" dropdown has a selected option
- Pill button group for the table tabs because I don't think our default tab layout ui will work well here.
- Thinking about using the [reactstrap table](https://reactstrap.github.io/components/tables/) to support search and pagination. Then just style it like the entity explorer table.

**Comment by fightingmonk** [comment]
Thanks for digging into this @danielgolden . Really appreciate your interest in cleaning up the layout and visual style. Your proposed layout is more vertically compact, which I like a lot. 

One factor I want to pay attention to on this is staying true to the controls available in the NR1 SDK / UI Toolkit. Couple of questions for discussion: 

1. Does shrinking the horizontal size of the table to add the version sidebar impact usability?
2. I haven't seen pill-style selectors in NR1. What about the normal tab style is bugging you? Would another Select dropdown in the header be better since this is effectively a filter similar to SLO and tag?
3. [React Table](https://www.npmjs.com/package/react-table) supports search and pagination. What about the reactstrap table is better?

**Comment by danielgolden** [comment]
No problem, @fightingmonk :). This is really helpful and great feedback. I'm going to include my responses below:

1. **Shrinking horizontal size impact usability?**: I think this will have a positive impact on usability by separating the version list from the rest of the content is reduces confusion around the list being a part of the interactable UI (which, if I'm understanding it correctly, is not interactable. Just a list of versions). It also could include a toggle button so that users can collapse the sidebar if they want/need more space.
2. **Why not normal tab styles?**: Though it _is_  pill shaped in the wireframe above I don't intent for it to actually look that way. The wireframe above is just meant to be like chicken stratch on a napkin. Really low fidelity to just get the idea of the layout down. Still I'm glad you pointed this out because that does represent a change of the UI element. Though rather than a pill styled selectors, I'm thinking a segmented control which is [used in NR1](https://user-images.githubusercontent.com/812989/68668492-4861a680-0516-11ea-86bf-512a1c1ce20f.png). My issues with the default NR1 3rd party tab controls are:
    - In this context they're hard to spot (even as I go and look for the tabs it takes me a bit to find them between the header and table). They blend in too well.
    - It doesn't offer many affordances to suggest that it's a tabs control. In other words, because it's just text with a line under it (both greyscale), it is not immediately distinguishable from our default input styes (also just text with a line under it) or a header with a line under it.
    - In contrast, a segmented control will include our primary button color and be a button shaped rectangle with slightly rounded corners). It matches a pattern of segmented controls that users are used to across the web, mobile, and NR1.
3. **Why not React Table?**: Oh, cool! I don't know why I was thinking it didn't support pagination or search. That's great, and should save some time. Thanks for bringing this up.

---
I'm working on this between other projects so I haven't been able to spend as much time on it as I wanted to the last few weeks, but hopefully I should be able to get out a high-fidelity mockup soon and post it here so we can iterate on that. Thanks again for your feedback @fightingmonk!

**Comment by danielgolden** [comment]
@fightingmonk I think the changes you've made have worked out great. I've been meaning to  create a more high-fidelity mockup that's based on the wireframe from above for a while and was finally able to create it today. I'd love your thoughts on what I'm proposing in this mockup:

<img width="1440" alt="Groundskeeper Redesing - draft 1" src="https://user-images.githubusercontent.com/812989/71626339-a3c92000-2bba-11ea-8bd0-b42ce3e5d7e8.png">

#### Significant updates:
- Moved the button group into the "options bar" so that it sits in context with "Loaded x applications" text.
- Omitted table pagination for simpler access to all of the data in the table (is there for potential for there to be enough rows of data for this to be a problem? e.g. 1000+ rows?)
- Reduced the number of search inputs from 6 to 1 universal search input
- Added column sorting for the "latest APM agents versions" table.


---
p.s. It was great to meet you in person a few weeks ago!

**Comment by tangollama** [comment]
Per @danielgolden 2.5 weeks of duration in and around other tasks. Awaiting feedback from @fightingmonk

**Comment by fightingmonk** [comment]
@danielgolden :100: on all the table changes you're suggesting! IMO you're describing exactly how it should work.

I'm not sold on the options bar proposal, partly because it's not a pattern I've seen used in the NR product UIs and putting them off to the right detaches them from the IA flow of the page. Would it be more consistent to use another Select element for them immediately to the right of the Filter picker?

i.e. the options bar would be 
**[SLO picker]  [Tag picker]  [Value picker _1_] [State picker _2_]**
and then the _loaded N applications_ could be right-justified as it's just informational.

1. Value picker is only visible when Tag picker has a name selected
2. State picker has options Out of date, Multiple versions, and Up to date

**Comment by danielgolden** [comment]
Good feedback on all points. Thanks, @fightingmonk.

The options bar is mostly a design pattern found in 3rd party nerdpacks because we do not have access to the global header where some of the items found in the options bar could live.

I have plans to work on this update which I'll submit in a PR next week (project load permitting). As Joel mentioned I think it will take about 2.5 weeks to go from start to completely finished (pr feedback changes and all).
