### ISSUE TITLE
Latest agent is showing up as "Out of date"

### ISSUE THREAD

**Issue by StacySimmons** [newrelic/nr1-groundskeeper#4]
## Description
Dotnet agents just updated are displayed as "out of date" The version shown installed is "8.20.262.0" while the "latest version" table displays as "8.20.262"

## Steps to Reproduce
Launch Agent Groundskeeper
Select "the latest agents" for upgrade SLO

## Expected Behaviour
There should be no applications listed under "Out of date" tab. All agents should be listed under "Up to date", as the version installed and the latest version are identical.

Additionally, the agent installed is three weeks old and should not be displayed if upgrade SLO is 1 month or 6 months.

## Screenshot of Output
![Agent_Groundskeeper___New_Relic_One](https://user-images.githubusercontent.com/24992650/68616405-f9bef880-0492-11ea-9f54-4d71df41c1c6.png)

**Comment by fightingmonk** [comment]
Thanks for the report @StaceySimmons . I see the problem...

For future me, the [current agent detection](https://github.com/newrelic/nr1-groundskeeper/blob/master/nerdlets/groundskeeper-nerdlet/index.js#L316) needs to use [fuzzy matching on reported agent version](https://github.com/newrelic/nr1-groundskeeper/blob/master/nerdlets/groundskeeper-nerdlet/index.js#L613-L615).
