### ISSUE TITLE
Add Latest Support Agent Version

### ISSUE THREAD

**Issue by 65pony** [newrelic/nr1-groundskeeper#55]
# Summary
[NOTE]: Add latest supported version to dashboard

# Description
[NOTE]: Adding latest support version to the dashboard would allow the customer and NR to better manager their agent deployments. It would also allow for customer to prioritize which agents need to be upgraded.

## Desired Behaviour

[NOTE]: # Add supported agent version beside the latest agent version in the UI

**Comment by fightingmonk** [comment]
@65pony thanks for the suggestion! I want to better understand your goal.

Currently you can set the Upgrade SLO to "< 1 year old (support cutoff)" and the Out of Date report will show any services running agents beyond support cutoff. 
![Screen Shot 2021-02-04 at 10 57 52 AM](https://user-images.githubusercontent.com/482671/106941707-094de100-66d8-11eb-8637-34396b64abc4.png)

Are you wanting to add the oldest supported agent version to the table on the right, or am I mis-understanding your goal?
![Screen Shot 2021-02-04 at 10 59 45 AM](https://user-images.githubusercontent.com/482671/106941786-2e425400-66d8-11eb-9f28-83a2584ad78e.png)

**Comment by aso1124** [comment]
Addressed in v2.0
