### ISSUE TITLE
Latest APM Agent versions table doesnt show latest versions, they are 10 years old

### ISSUE THREAD

**Issue by jsbnr** [newrelic/nr1-groundskeeper#64]
## Description
The latest APM Agent table on the right hand side shows versions from 2011. Pretty sure these are not the latest versions!

## Steps to Reproduce

View the table on the right

## Expected Behaviour

I expect to see the latest version number for each agent, and i expect them not to be 10 years old

<img width="396" alt="image" src="https://user-images.githubusercontent.com/55132258/133322038-1d00dc30-8316-4cc9-993a-32bb801547f0.png">

**Comment by aso1124** [comment]
The report in v2.0 now shows the latest agent version compatible with the language version used by the application.
