### ISSUE TITLE
Groundskeeper not functioning in NR1 production

### ISSUE THREAD

**Issue by ferdinand-p** [newrelic/nr1-groundskeeper#68]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Groundskeeper is not functioning in production, all accounts)
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used:
* Browser name and version:
* Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by tdallmann** [comment]
Also experiencing this - only result when trying to run app is "Oops - something went wrong"

**Comment by throck** [comment]
Should be working again now - there was an issue with the agent release metadata, but it was fixed in [this commit](https://github.com/newrelic/docs-website/commit/9fcbca271a1051283a88a7c5b03b9458befc9d05)
